name: Url HealthCheck

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '1, 1 * * *'



jobs:
  simple_url_healthcheck:
    runs-on: ubuntu-18.04
    steps:
      - name: Check url 
        uses: jtalk/url-health-check-action@v2
        with:
          # Check the following URLs one by one sequentially
          url: https://pokedexhaksa.herokuapp.com/health|https://pokedexhaksa.herokuapp.com/version
          max-attempts: 3 # Optional, defaults to 1
          # Delay between retries
          retry-delay: 5s # Optional, only applicable to max-attempts > 1
          # Retry all errors, including 404. This option might trigger curl upgrade.